apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-management-system
  namespace: gym-system
  labels:
    app: gym-management-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gym-management-system
  template:
    metadata:
      labels:
        app: gym-management-system
    spec:
      containers:
      - name: gym-backend
        image: saim814/gym-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri
              key: MONGO_URI
      - name: gym-frontend
        image: saim814/gym-frontend:latest # Replace with your actual Docker Hub username
        ports:
        - containerPort: 80