apiVersion: v1
kind: Service
metadata:
  name: gym-management-service
  namespace: gym-system
spec:
  type: NodePort
  selector:
    app: gym-management-system
  ports:
    - name: backend
      port: 5000
      targetPort: 5000
      nodePort: 31007
    - name: frontend
      port: 80
      targetPort: 80
      nodePort: 31008